# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
      - release/*
    
  
  tags:
    include:
      - refs/tags/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - bash: |
        TAG=$(Build.SourceBranchName)
        echo "Tag: $TAG"
        echo "##vso[task.setvariable variable=TAG_NUMBER]$TAG"
      displayName: 'Extract and Set Git Tag Number $(Build.SourceBranchName)'

    - script: echo $(TAG_NUMBER)
      displayName: 'Print Tag Number'
    
    - task: Docker@2
      displayName: "the build and push command"
      inputs:
        containerRegistry: 'dockerhubregistry'
        repository: 'ayoubalgharrass/testimageatelierdotnet'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile' 
        tags: |
          $(Build.SourceBranchName)
          latest
        