# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
      - release/*
    
  
  tags:
    include:
      - refs/tags/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
  
    - script: |
        $tag = git describe --tags --abbrev=0
        echo "Tag showwwwwwwwwwww: $($tag)"
        $env:TAG_NUMBER = $tag
        echo $(TAG_NUMBER)
      displayName:  "the tag:::: tag name = $(TAG_NUMBER)  or tag = $(tag)  "


    - task: Docker@2
      displayName: "the build and push command"
      inputs:
        containerRegistry: 'dockerhubregistry'
        repository: 'ayoubalgharrass/testimageatelierdotnet'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile' 
        tags: $(TAG_NUMBER)
          