# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
      - release/*
    
  
  tags:
    include:
      - refs/tags/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - bash: |
        TAG=$(git describe --tags --abbrev=0)
        echo "Tag: $TAG"
        echo "##vso[task.setvariable variable=TAG_NUMBER]$TAG"
      displayName: 'Extract and Set Git Tag Number $(TAG)'

    - script: echo $(TAG_NUMBER)
      displayName: 'Print Tag Number'
      
    - script: |
        $tag = $(git describe --tags --abbrev=0)
        echo "Tag showwwwwwwwwwww: $(tag) others: refs/tags/*= $(refs/tags/*) "
      displayName:  "the tag:::: t or tag   = $(tag)  "

    - script: |
        if [ "$(Build.SourceBranch)" == "refs/tags/*" ]; then
          tagName=$(Build.SourceBranch | sed 's#refs/tags/##')
          echo "Tag Name: $tagName"
        else
          echo "Not a tag branch."
        fi
      displayName: 'Extract Tag Information'
      
  


    - task: Docker@2
      displayName: "the build and push command"
      inputs:
        containerRegistry: 'dockerhubregistry'
        repository: 'ayoubalgharrass/testimageatelierdotnet'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile' 
        
          